### ISSUE TITLE
Почему TreeSet?

### ISSUE THREAD

**Issue by DeKinci** [GoHackathonTeam/WanaFriend#1]
Зачем?

**Comment by Ktlo** [comment]
Я подумал, что это как раз тот случай, когда это будет полезно. При больших объёмах данных (мало ли друзей у друзей) поиск может ускорить сама структура сета

**Comment by DeKinci** [comment]
А добавлять большие объемы данных не долговато будет? Тем более, HashSet тоже быстро ищет, особенно по Integer, у которого коллизий не бывает. 
Тем более, что-то я не вижу использования поиска)

**Comment by Ktlo** [comment]
Ну для того чтобы ему не добавить тот же элемент, что уже там есть, необходимо осуществить поиск. И далеко не факт, что все эти большие объемы данных будут абсолютно разными идентификаторами.
Возможно на случайных числах следует проверить скорость.

**Comment by DeKinci** [comment]
В принципе вот, чтобы не повторять спор, замечательный человек RodionGork все хорошо рассказывает
https://javatalks.ru/topics/41666

P.S. как уже говорил ранее, у интеджеров коллизий быть не может
P.P.S. Спойлер: у хэшмапы O(1) против O(logN) у тримапы
P.P.P.S. Я как раз написал стенд для проверки этой задачи на скорость, так что не проблема

**Comment by Ktlo** [comment]
Сейчас сам проверял, действительно HashSet в общем случае работает быстрее. Поменял на него.

**Comment by DeKinci** [comment]
На гитхабе есть фишка с закрытием issue commit'ом, чтобы было понятно, когда была решена проблема. Полезная штука
