### ISSUE TITLE
Добавить бы .gitignore

### ISSUE THREAD

**Issue by DeKinci** [GoHackathonTeam/WanaFriend#2]
Полезная штука. Нечего людям свои файлы .idea показывать.

**Comment by Ktlo** [comment]
Знаю, что штука полезная важная и нужная, но про то что файлы идеи тайна великая не слышал, но так и быть спрячу.

**Comment by DeKinci** [comment]
Не в тайне дело, а в том, что когда толпой над проектом работать будем, если кто попробует pull сделать, его идейные файлы начнут конфликтовать с файлами отправителя и получиться вакханалия
